; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\Ali\Desktop\OperatingSystem\SystemCore\SysCore\Kernel\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAHPAUmultiboot_info@@@Z		; kernel_entry
EXTRN	_main:PROC
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\operatingsystem\systemcore\syscore\kernel\entry.cpp
_TEXT	SEGMENT
_info$ = 8						; size = 4
?kernel_entry@@YAHPAUmultiboot_info@@@Z PROC		; kernel_entry

; 8    : #ifdef ARCH_X86
; 9    : 	// Set register
; 10   : 	_asm {
; 11   : 		cli 

	cli

; 12   : 		mov ax,10h

	mov	ax, 16					; 00000010H

; 13   : 		mov ds,ax 

	mov	ds, ax

; 14   : 		mov es,ax 

	mov	es, ax

; 15   : 		mov fs,ax 

	mov	fs, ax

; 16   : 		mov gs,ax 

	mov	gs, ax

; 17   : 	}
; 18   : #endif
; 19   : 	
; 20   : 	main(info);

	push	DWORD PTR _info$[esp-4]
	call	_main
	add	esp, 4

; 24   : 		cli 

	cli

; 25   : 		hlt

	hlt
	npad	1

; 21   : 
; 22   : #ifdef ARCH_X86
; 23   : 	_asm {

$LL2@kernel_ent:

; 26   : 	}
; 27   : #endif
; 28   : 
; 29   : 	while (1);

	jmp	SHORT $LL2@kernel_ent
?kernel_entry@@YAHPAUmultiboot_info@@@Z ENDP		; kernel_entry
_TEXT	ENDS
END
