; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\ali\Desktop\OperatingSystem\SystemCore\SysCore\Kernel\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAHXZ				; kernel_entry
EXTRN	_main:PROC
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\operatingsystem\systemcore\syscore\kernel\entry.cpp
_TEXT	SEGMENT
?kernel_entry@@YAHXZ PROC				; kernel_entry

; 6    : #ifdef ARCH_X86
; 7    : 	// Set register
; 8    : 	_asm {
; 9    : 		cli 

	cli

; 10   : 		mov ax,10h

	mov	ax, 16					; 00000010H

; 11   : 		mov ds,ax 

	mov	ds, ax

; 12   : 		mov es,ax 

	mov	es, ax

; 13   : 		mov fs,ax 

	mov	fs, ax

; 14   : 		mov gs,ax 

	mov	gs, ax

; 15   : 	}
; 16   : #endif
; 17   : 	
; 18   : 	main();

	call	_main

; 22   : 		cli 

	cli

; 23   : 		hlt

	hlt

; 19   : 
; 20   : #ifdef ARCH_X86
; 21   : 	_asm {

$LL2@kernel_ent:

; 24   : 	}
; 25   : #endif
; 26   : 
; 27   : 	while (1);

	jmp	SHORT $LL2@kernel_ent
?kernel_entry@@YAHXZ ENDP				; kernel_entry
_TEXT	ENDS
END
