; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\Ali\Desktop\OperatingSystem\SystemCore\SysCore\Kernel\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG2760	DB	'    Mango  Operating System is Loading ....             '
	DB	'                        ', 00H
	ORG $+3
$SG2761	DB	'we are optimizing th operating system WindowsX!', 0aH, 00H
	ORG $+3
$SG2762	DB	'CTRL+ALT+DEL to restart                                 '
	DB	'                        ', 00H
	ORG $+3
$SG2769	DB	'Count = %d       ', 00H
CONST	ENDS
PUBLIC	_main
EXTRN	?DebugGotoXY@@YAXEE@Z:PROC			; DebugGotoXY
EXTRN	?DebugClrScreen@@YAXE@Z:PROC			; DebugClrScreen
EXTRN	?DebugSetColor@@YAXG@Z:PROC			; DebugSetColor
EXTRN	?DebugPuts@@YAXPAD@Z:PROC			; DebugPuts
EXTRN	?DebugPrintf@@YAHPBDZZ:PROC			; DebugPrintf
EXTRN	?hal_initialize@@YAXXZ:PROC			; hal_initialize
EXTRN	?setvect@@YAXIA6AXXZ@Z:PROC			; setvect
EXTRN	?interrupt_enable@@YAXXZ:PROC			; interrupt_enable
EXTRN	?get_tick@@YAIXZ:PROC				; get_tick
EXTRN	?divide_by_zero_fault@@YAXIII@Z:PROC		; divide_by_zero_fault
EXTRN	?single_step_trap@@YAXIII@Z:PROC		; single_step_trap
EXTRN	?nmi_trap@@YAXIII@Z:PROC			; nmi_trap
EXTRN	?breakpoint_trap@@YAXIII@Z:PROC			; breakpoint_trap
EXTRN	?overflow_trap@@YAXIII@Z:PROC			; overflow_trap
EXTRN	?bounds_check_fault@@YAXIII@Z:PROC		; bounds_check_fault
EXTRN	?invalid_opcode_fault@@YAXIII@Z:PROC		; invalid_opcode_fault
EXTRN	?no_device_fault@@YAXIII@Z:PROC			; no_device_fault
EXTRN	?double_fault_abort@@YAXIIII@Z:PROC		; double_fault_abort
EXTRN	?invalid_tss_fault@@YAXIIII@Z:PROC		; invalid_tss_fault
EXTRN	?no_segment_fault@@YAXIIII@Z:PROC		; no_segment_fault
EXTRN	?stack_fault@@YAXIIII@Z:PROC			; stack_fault
EXTRN	?general_protection_fault@@YAXIIII@Z:PROC	; general_protection_fault
EXTRN	?page_fault@@YAXIIII@Z:PROC			; page_fault
EXTRN	?fpu_fault@@YAXIII@Z:PROC			; fpu_fault
EXTRN	?alignment_check_fault@@YAXIIII@Z:PROC		; alignment_check_fault
EXTRN	?machine_check_abort@@YAXIII@Z:PROC		; machine_check_abort
EXTRN	?simd_fpu_fault@@YAXIII@Z:PROC			; simd_fpu_fault
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\operatingsystem\systemcore\syscore\kernel\main.cpp
_TEXT	SEGMENT
_main	PROC

; 7    : 	hal_initialize();

	call	?hal_initialize@@YAXXZ			; hal_initialize

; 8    : 	//! install our exception handlers
; 9    : 	setvect(0, (void(__cdecl &)(void))divide_by_zero_fault);

	push	OFFSET ?divide_by_zero_fault@@YAXIII@Z	; divide_by_zero_fault
	push	0
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 10   : 	setvect(1, (void(__cdecl &)(void))single_step_trap);

	push	OFFSET ?single_step_trap@@YAXIII@Z	; single_step_trap
	push	1
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 11   : 	setvect(2, (void(__cdecl &)(void))nmi_trap);

	push	OFFSET ?nmi_trap@@YAXIII@Z		; nmi_trap
	push	2
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 12   : 	setvect(3, (void(__cdecl &)(void))breakpoint_trap);

	push	OFFSET ?breakpoint_trap@@YAXIII@Z	; breakpoint_trap
	push	3
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 13   : 	setvect(4, (void(__cdecl &)(void))overflow_trap);

	push	OFFSET ?overflow_trap@@YAXIII@Z		; overflow_trap
	push	4
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 14   : 	setvect(5, (void(__cdecl &)(void))bounds_check_fault);

	push	OFFSET ?bounds_check_fault@@YAXIII@Z	; bounds_check_fault
	push	5
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 15   : 	setvect(6, (void(__cdecl &)(void))invalid_opcode_fault);

	push	OFFSET ?invalid_opcode_fault@@YAXIII@Z	; invalid_opcode_fault
	push	6
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 16   : 	setvect(7, (void(__cdecl &)(void))no_device_fault);

	push	OFFSET ?no_device_fault@@YAXIII@Z	; no_device_fault
	push	7
	call	?setvect@@YAXIA6AXXZ@Z			; setvect
	add	esp, 64					; 00000040H

; 17   : 	setvect(8, (void(__cdecl &)(void))double_fault_abort);

	push	OFFSET ?double_fault_abort@@YAXIIII@Z	; double_fault_abort
	push	8
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 18   : 	setvect(10, (void(__cdecl &)(void))invalid_tss_fault);

	push	OFFSET ?invalid_tss_fault@@YAXIIII@Z	; invalid_tss_fault
	push	10					; 0000000aH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 19   : 	setvect(11, (void(__cdecl &)(void))no_segment_fault);

	push	OFFSET ?no_segment_fault@@YAXIIII@Z	; no_segment_fault
	push	11					; 0000000bH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 20   : 	setvect(12, (void(__cdecl &)(void))stack_fault);

	push	OFFSET ?stack_fault@@YAXIIII@Z		; stack_fault
	push	12					; 0000000cH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 21   : 	setvect(13, (void(__cdecl &)(void))general_protection_fault);

	push	OFFSET ?general_protection_fault@@YAXIIII@Z ; general_protection_fault
	push	13					; 0000000dH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 22   : 	setvect(14, (void(__cdecl &)(void))page_fault);

	push	OFFSET ?page_fault@@YAXIIII@Z		; page_fault
	push	14					; 0000000eH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 23   : 	setvect(16, (void(__cdecl &)(void))fpu_fault);

	push	OFFSET ?fpu_fault@@YAXIII@Z		; fpu_fault
	push	16					; 00000010H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 24   : 	setvect(17, (void(__cdecl &)(void))alignment_check_fault);

	push	OFFSET ?alignment_check_fault@@YAXIIII@Z ; alignment_check_fault
	push	17					; 00000011H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect
	add	esp, 64					; 00000040H

; 25   : 	setvect(18, (void(__cdecl &)(void))machine_check_abort);

	push	OFFSET ?machine_check_abort@@YAXIII@Z	; machine_check_abort
	push	18					; 00000012H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 26   : 	setvect(19, (void(__cdecl &)(void))simd_fpu_fault);

	push	OFFSET ?simd_fpu_fault@@YAXIII@Z	; simd_fpu_fault
	push	19					; 00000013H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 27   : 	interrupt_enable();

	call	?interrupt_enable@@YAXXZ		; interrupt_enable

; 28   : 	DebugClrScreen(0x1f);

	push	31					; 0000001fH
	call	?DebugClrScreen@@YAXE@Z			; DebugClrScreen

; 29   : 	DebugSetColor(0x78);

	push	120					; 00000078H
	call	?DebugSetColor@@YAXG@Z			; DebugSetColor

; 30   : 	DebugPuts("    Mango  Operating System is Loading ....                                     ");

	push	OFFSET $SG2760
	call	?DebugPuts@@YAXPAD@Z			; DebugPuts

; 31   : 	DebugSetColor(0x19);

	push	25					; 00000019H
	call	?DebugSetColor@@YAXG@Z			; DebugSetColor

; 32   : 	DebugPuts("we are optimizing th operating system WindowsX!\n");

	push	OFFSET $SG2761
	call	?DebugPuts@@YAXPAD@Z			; DebugPuts

; 33   : 	DebugGotoXY(0, 24);

	push	24					; 00000018H
	push	0
	call	?DebugGotoXY@@YAXEE@Z			; DebugGotoXY

; 34   : 	DebugSetColor(0x78);

	push	120					; 00000078H
	call	?DebugSetColor@@YAXG@Z			; DebugSetColor

; 35   : 	DebugPuts("CTRL+ALT+DEL to restart                                                         ");

	push	OFFSET $SG2762
	call	?DebugPuts@@YAXPAD@Z			; DebugPuts
	add	esp, 52					; 00000034H
	npad	2
$LL2@main:

; 36   : 	//INT(16);
; 37   : 	int a = 0;
; 38   : 	int b = 1;
; 39   : 	int c = 0;
; 40   : 	c = b / a;
; 41   : 	for (;;){
; 42   : 		DebugGotoXY(0, 12);

	push	12					; 0000000cH
	push	0
	call	?DebugGotoXY@@YAXEE@Z			; DebugGotoXY

; 43   : 		DebugPrintf("Count = %d       ", get_tick());

	call	?get_tick@@YAIXZ			; get_tick
	push	eax
	push	OFFSET $SG2769
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf
	add	esp, 16					; 00000010H

; 44   : 	}

	jmp	SHORT $LL2@main
_main	ENDP
_TEXT	ENDS
END
