; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\Ali\Desktop\MangOS\SystemCore\SysCore\Kernel\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?kernel_initialize@@YAHPAUmultiboot_info@@@Z	; kernel_initialize
PUBLIC	_main
EXTRN	?DebugPutc@@YAXE@Z:PROC				; DebugPutc
EXTRN	?DebugGotoXY@@YAXEE@Z:PROC			; DebugGotoXY
EXTRN	?DebugClrScreen@@YAXE@Z:PROC			; DebugClrScreen
EXTRN	?hal_initialize@@YAXXZ:PROC			; hal_initialize
EXTRN	?setvect@@YAXIA6AXXZ@Z:PROC			; setvect
EXTRN	?interrupt_enable@@YAXXZ:PROC			; interrupt_enable
EXTRN	?divide_by_zero_fault@@YAXIII@Z:PROC		; divide_by_zero_fault
EXTRN	?single_step_trap@@YAXIII@Z:PROC		; single_step_trap
EXTRN	?nmi_trap@@YAXIII@Z:PROC			; nmi_trap
EXTRN	?breakpoint_trap@@YAXIII@Z:PROC			; breakpoint_trap
EXTRN	?overflow_trap@@YAXIII@Z:PROC			; overflow_trap
EXTRN	?bounds_check_fault@@YAXIII@Z:PROC		; bounds_check_fault
EXTRN	?invalid_opcode_fault@@YAXIII@Z:PROC		; invalid_opcode_fault
EXTRN	?no_device_fault@@YAXIII@Z:PROC			; no_device_fault
EXTRN	?double_fault_abort@@YAXIIII@Z:PROC		; double_fault_abort
EXTRN	?invalid_tss_fault@@YAXIIII@Z:PROC		; invalid_tss_fault
EXTRN	?no_segment_fault@@YAXIIII@Z:PROC		; no_segment_fault
EXTRN	?stack_fault@@YAXIIII@Z:PROC			; stack_fault
EXTRN	?general_protection_fault@@YAXIIII@Z:PROC	; general_protection_fault
EXTRN	?page_fault@@YAXIIII@Z:PROC			; page_fault
EXTRN	?fpu_fault@@YAXIII@Z:PROC			; fpu_fault
EXTRN	?alignment_check_fault@@YAXIIII@Z:PROC		; alignment_check_fault
EXTRN	?machine_check_abort@@YAXIII@Z:PROC		; machine_check_abort
EXTRN	?simd_fpu_fault@@YAXIII@Z:PROC			; simd_fpu_fault
EXTRN	?pmm_initialize@@YAXII@Z:PROC			; pmm_initialize
EXTRN	?pmm_set_region@@YAXII@Z:PROC			; pmm_set_region
EXTRN	?pmm_clr_region@@YAXII@Z:PROC			; pmm_clr_region
EXTRN	?vmm_initialize@@YAXXZ:PROC			; vmm_initialize
EXTRN	?kbrd_initilize@@YAXXZ:PROC			; kbrd_initilize
EXTRN	?kbrd_get_last_std_char@@YAEXZ:PROC		; kbrd_get_last_std_char
EXTRN	?kbrd_destroy_last_char@@YAXXZ:PROC		; kbrd_destroy_last_char
EXTRN	?kbrd_make@@YAEE@Z:PROC				; kbrd_make
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\main.cpp
_TEXT	SEGMENT
_ch$ = -4						; size = 1
_info$ = 8						; size = 4
_main	PROC

; 70   : int _cdecl main (multiboot_info* info) {

	push	ecx

; 71   : 	kernel_initialize(info);

	push	DWORD PTR _info$[esp]
	call	?kernel_initialize@@YAHPAUmultiboot_info@@@Z ; kernel_initialize

; 72   : 	DebugClrScreen(0x1f);

	push	31					; 0000001fH
	call	?DebugClrScreen@@YAXE@Z			; DebugClrScreen

; 73   : 	DebugGotoXY(0, 0);

	push	0
	push	0
	call	?DebugGotoXY@@YAXEE@Z			; DebugGotoXY
	add	esp, 16					; 00000010H
	npad	3
$LL2@main:

; 74   : 	uint8_t ch;
; 75   : 	for (;;){
; 76   : 		while (kbrd_get_last_std_char() == 0);

	call	?kbrd_get_last_std_char@@YAEXZ		; kbrd_get_last_std_char
	test	al, al
	je	SHORT $LL2@main

; 77   : 		ch = kbrd_make(kbrd_get_last_std_char());

	call	?kbrd_get_last_std_char@@YAEXZ		; kbrd_get_last_std_char
	movzx	eax, al
	push	eax
	call	?kbrd_make@@YAEE@Z			; kbrd_make
	mov	BYTE PTR _ch$[esp+8], al

; 78   : 		DebugPutc(ch);

	push	DWORD PTR _ch$[esp+8]
	call	?DebugPutc@@YAXE@Z			; DebugPutc
	add	esp, 8

; 79   : 		kbrd_destroy_last_char();

	call	?kbrd_destroy_last_char@@YAXXZ		; kbrd_destroy_last_char

; 80   : 	}

	jmp	SHORT $LL2@main
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\main.cpp
_TEXT	SEGMENT
_kernel_img_size$ = -4					; size = 4
_info$ = 8						; size = 4
?kernel_initialize@@YAHPAUmultiboot_info@@@Z PROC	; kernel_initialize

; 19   : int _cdecl kernel_initialize (multiboot_info* info) {

	push	ecx
	push	esi
	push	edi

; 20   : 	uint32_t kernel_img_size;
; 21   : 	_asm mov word ptr[kernel_img_size], dx /*Get Kernel Image Size form Bootloader*/

	mov	WORD PTR _kernel_img_size$[esp+12], dx

; 22   : 	hal_initialize();

	call	?hal_initialize@@YAXXZ			; hal_initialize

; 23   : 
; 24   : 	//! install our exception handlers
; 25   : 	setvect(0, (void(__cdecl &)(void))divide_by_zero_fault);

	push	OFFSET ?divide_by_zero_fault@@YAXIII@Z	; divide_by_zero_fault
	push	0
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 26   : 	setvect(1, (void(__cdecl &)(void))single_step_trap);

	push	OFFSET ?single_step_trap@@YAXIII@Z	; single_step_trap
	push	1
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 27   : 	setvect(2, (void(__cdecl &)(void))nmi_trap);

	push	OFFSET ?nmi_trap@@YAXIII@Z		; nmi_trap
	push	2
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 28   : 	setvect(3, (void(__cdecl &)(void))breakpoint_trap);

	push	OFFSET ?breakpoint_trap@@YAXIII@Z	; breakpoint_trap
	push	3
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 29   : 	setvect(4, (void(__cdecl &)(void))overflow_trap);

	push	OFFSET ?overflow_trap@@YAXIII@Z		; overflow_trap
	push	4
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 30   : 	setvect(5, (void(__cdecl &)(void))bounds_check_fault);

	push	OFFSET ?bounds_check_fault@@YAXIII@Z	; bounds_check_fault
	push	5
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 31   : 	setvect(6, (void(__cdecl &)(void))invalid_opcode_fault);

	push	OFFSET ?invalid_opcode_fault@@YAXIII@Z	; invalid_opcode_fault
	push	6
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 32   : 	setvect(7, (void(__cdecl &)(void))no_device_fault);

	push	OFFSET ?no_device_fault@@YAXIII@Z	; no_device_fault
	push	7
	call	?setvect@@YAXIA6AXXZ@Z			; setvect
	add	esp, 64					; 00000040H

; 33   : 	setvect(8, (void(__cdecl &)(void))double_fault_abort);

	push	OFFSET ?double_fault_abort@@YAXIIII@Z	; double_fault_abort
	push	8
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 34   : 	setvect(10, (void(__cdecl &)(void))invalid_tss_fault);

	push	OFFSET ?invalid_tss_fault@@YAXIIII@Z	; invalid_tss_fault
	push	10					; 0000000aH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 35   : 	setvect(11, (void(__cdecl &)(void))no_segment_fault);

	push	OFFSET ?no_segment_fault@@YAXIIII@Z	; no_segment_fault
	push	11					; 0000000bH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 36   : 	setvect(12, (void(__cdecl &)(void))stack_fault);

	push	OFFSET ?stack_fault@@YAXIIII@Z		; stack_fault
	push	12					; 0000000cH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 37   : 	setvect(13, (void(__cdecl &)(void))general_protection_fault);

	push	OFFSET ?general_protection_fault@@YAXIIII@Z ; general_protection_fault
	push	13					; 0000000dH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 38   : 	setvect(14, (void(__cdecl &)(void))page_fault);

	push	OFFSET ?page_fault@@YAXIIII@Z		; page_fault
	push	14					; 0000000eH
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 39   : 	setvect(16, (void(__cdecl &)(void))fpu_fault);

	push	OFFSET ?fpu_fault@@YAXIII@Z		; fpu_fault
	push	16					; 00000010H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 40   : 	setvect(17, (void(__cdecl &)(void))alignment_check_fault);

	push	OFFSET ?alignment_check_fault@@YAXIIII@Z ; alignment_check_fault
	push	17					; 00000011H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect
	add	esp, 64					; 00000040H

; 41   : 	setvect(18, (void(__cdecl &)(void))machine_check_abort);

	push	OFFSET ?machine_check_abort@@YAXIII@Z	; machine_check_abort
	push	18					; 00000012H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 42   : 	setvect(19, (void(__cdecl &)(void))simd_fpu_fault);

	push	OFFSET ?simd_fpu_fault@@YAXIII@Z	; simd_fpu_fault
	push	19					; 00000013H
	call	?setvect@@YAXIA6AXXZ@Z			; setvect

; 43   : 	kbrd_initilize();

	call	?kbrd_initilize@@YAXXZ			; kbrd_initilize

; 44   : 	interrupt_enable(); /*Enabling interrupt*/

	call	?interrupt_enable@@YAXXZ		; interrupt_enable

; 45   : 
; 46   : 	unsigned int memory_amount = 1024;
; 47   : 	memory_amount += info->m_memoryLo;
; 48   : 	memory_amount += info->m_memoryHi * 64;
; 49   : 	pmm_initialize(memory_amount,0x100000+kernel_img_size*512);

	mov	eax, DWORD PTR _kernel_img_size$[esp+28]
	add	eax, 2048				; 00000800H
	shl	eax, 9
	push	eax
	mov	eax, DWORD PTR _info$[esp+28]
	mov	ecx, DWORD PTR [eax+8]
	add	ecx, 16					; 00000010H
	shl	ecx, 6
	add	ecx, DWORD PTR [eax+4]
	push	ecx
	call	?pmm_initialize@@YAXII@Z		; pmm_initialize

; 50   : 
; 51   : 
; 52   : 	memory_region *mem_mep = (memory_region*)0x1000;
; 53   : 	DebugGotoXY(0, 3);

	push	3
	push	0
	call	?DebugGotoXY@@YAXEE@Z			; DebugGotoXY
	add	esp, 32					; 00000020H
	mov	esi, 4096				; 00001000H

; 54   : 	for (int i = 0; i < 15; i++){

	xor	edi, edi
	npad	5
$LL5@kernel_ini:

; 55   : 		if (i>0 && mem_mep[i].startLow == 0)

	test	edi, edi
	jle	SHORT $LN2@kernel_ini
	cmp	DWORD PTR [esi], 0
	je	SHORT $LN9@kernel_ini
$LN2@kernel_ini:

; 56   : 			break;
; 57   : 		if (mem_mep[i].type == 1)	/*We Can Use it region*/

	cmp	DWORD PTR [esi+16], 1
	jne	SHORT $LN4@kernel_ini

; 58   : 			 pmm_clr_region(mem_mep[i].startLow, mem_mep[i].sizeLow);

	push	DWORD PTR [esi+8]
	push	DWORD PTR [esi]
	call	?pmm_clr_region@@YAXII@Z		; pmm_clr_region
	add	esp, 8
$LN4@kernel_ini:

; 54   : 	for (int i = 0; i < 15; i++){

	add	esi, 24					; 00000018H
	inc	edi
	cmp	esi, 4456				; 00001168H
	jl	SHORT $LL5@kernel_ini
$LN9@kernel_ini:

; 59   : 	}
; 60   : 	pmm_set_region(0x100000,kernel_img_size*512);

	mov	eax, DWORD PTR _kernel_img_size$[esp+12]
	shl	eax, 9
	push	eax
	push	1048576					; 00100000H
	call	?pmm_set_region@@YAXII@Z		; pmm_set_region
	add	esp, 8
	pop	edi
	pop	esi

; 62   : }

	add	esp, 4

; 61   : 	vmm_initialize();

	jmp	?vmm_initialize@@YAXXZ			; vmm_initialize
?kernel_initialize@@YAHPAUmultiboot_info@@@Z ENDP	; kernel_initialize
_TEXT	ENDS
END
