; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\Ali\Desktop\MangOS\SystemCore\SysCore\Kernel\panic.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG2655	DB	'We apologize, MOS has encountered a problem and has been'
	DB	' shut down', 0aH, 09H, 09H, 09H, 09H, 09H, '  to prevent dama'
	DB	'ge to your computer. Any unsaved work might be lost.', 0aH, 09H
	DB	09H, 09H, 09H, 09H, '  We are sorry for the inconvenience this'
	DB	' might have caused.', 0aH, 0aH, 09H, 09H, 09H, 09H, 09H, '  P'
	DB	'lease report the following information and restart your compu'
	DB	'ter.', 0aH, 09H, 09H, 09H, 09H, 09H, '  The system has been h'
	DB	'alted.', 0aH, 0aH, 00H
$SG2656	DB	'*** STOP: %s', 00H
CONST	ENDS
PUBLIC	?kernel_panic@@YAXPBDZZ				; kernel_panic
EXTRN	?interrupt_disable@@YAXXZ:PROC			; interrupt_disable
EXTRN	?DebugGotoXY@@YAXEE@Z:PROC			; DebugGotoXY
EXTRN	?DebugClrScreen@@YAXE@Z:PROC			; DebugClrScreen
EXTRN	?DebugSetColor@@YAXG@Z:PROC			; DebugSetColor
EXTRN	?DebugPuts@@YAXPAD@Z:PROC			; DebugPuts
EXTRN	?DebugPrintf@@YAHPBDZZ:PROC			; DebugPrintf
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\panic.cpp
_TEXT	SEGMENT
_fmt$ = 8						; size = 4
?kernel_panic@@YAXPBDZZ PROC				; kernel_panic

; 13   : 
; 14   : 	interrupt_disable();

	call	?interrupt_disable@@YAXXZ		; interrupt_disable

; 15   : 
; 16   : 	va_list		args;
; 17   : 	static char buf[1024];
; 18   : 
; 19   : 	va_start(args, fmt);
; 20   : 
; 21   : 	// We will need a vsprintf() here. I will see if I can write
; 22   : 	// one before the tutorial release
; 23   : 
; 24   : 	va_end(args);
; 25   : 
; 26   : 	char* disclamer = "We apologize, MOS has encountered a problem and has been shut down\n\
; 27   : 					  to prevent damage to your computer. Any unsaved work might be lost.\n\
; 28   : 					  We are sorry for the inconvenience this might have caused.\n\n\
; 29   : 					  Please report the following information and restart your computer.\n\
; 30   : 					  The system has been halted.\n\n";
; 31   : 
; 32   : 	DebugClrScreen(0x1f);

	push	31					; 0000001fH
	call	?DebugClrScreen@@YAXE@Z			; DebugClrScreen

; 33   : 	DebugGotoXY(0, 0);

	push	0
	push	0
	call	?DebugGotoXY@@YAXEE@Z			; DebugGotoXY

; 34   : 	DebugSetColor(0x1f);

	push	31					; 0000001fH
	call	?DebugSetColor@@YAXG@Z			; DebugSetColor

; 35   : 	DebugPuts(disclamer);

	push	OFFSET $SG2655
	call	?DebugPuts@@YAXPAD@Z			; DebugPuts

; 36   : 
; 37   : 	DebugPrintf("*** STOP: %s", fmt);

	push	DWORD PTR _fmt$[esp+16]
	push	OFFSET $SG2656
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf
	add	esp, 28					; 0000001cH
$LL2@kernel_pan:

; 38   : 
; 39   : 	for (;;);

	jmp	SHORT $LL2@kernel_pan
?kernel_panic@@YAXPBDZZ ENDP				; kernel_panic
_TEXT	ENDS
END
