; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\Ali\Desktop\MangOS\SystemCore\SysCore\Kernel\vmm.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?vmm_load_pdbr@@YAXPAUpdir@@@Z			; vmm_load_pdbr
PUBLIC	?vmm_get_cur_dir@@YAPAUpdir@@XZ			; vmm_get_cur_dir
PUBLIC	?vmm_alloc_frame@@YA_NPAI@Z			; vmm_alloc_frame
PUBLIC	?vmm_free_frame@@YA_NPAI@Z			; vmm_free_frame
PUBLIC	?vmm_map_page@@YAXPAX0@Z			; vmm_map_page
PUBLIC	?vmm_initialize@@YAXXZ				; vmm_initialize
PUBLIC	?vmm_pd_entry_add_attrib@@YAXPAII@Z		; vmm_pd_entry_add_attrib
PUBLIC	?vmm_pd_entry_del_attrib@@YAXPAII@Z		; vmm_pd_entry_del_attrib
PUBLIC	?vmm_pd_entry_set_frame@@YAXPAII@Z		; vmm_pd_entry_set_frame
PUBLIC	?vmm_pd_entry_is_present@@YA_NI@Z		; vmm_pd_entry_is_present
PUBLIC	?vmm_pd_entry_is_user@@YA_NI@Z			; vmm_pd_entry_is_user
PUBLIC	?vmm_pd_entry_is_4mb@@YA_NI@Z			; vmm_pd_entry_is_4mb
PUBLIC	?vmm_pt_entry_add_attrib@@YAXPAII@Z		; vmm_pt_entry_add_attrib
PUBLIC	?vmm_pt_entry_del_attrib@@YAXPAII@Z		; vmm_pt_entry_del_attrib
PUBLIC	?vmm_pt_entry_set_frame@@YAXPAII@Z		; vmm_pt_entry_set_frame
PUBLIC	?vmm_pt_entry_is_present@@YA_NI@Z		; vmm_pt_entry_is_present
PUBLIC	?vmm_pt_entry_is_writable@@YA_NI@Z		; vmm_pt_entry_is_writable
PUBLIC	?vmm_paging_enable@@YAX_N@Z			; vmm_paging_enable
PUBLIC	?vmm_pd_switch@@YA_NPAUpdir@@@Z			; vmm_pd_switch
PUBLIC	?vmm_flush_tlb_entry@@YAXI@Z			; vmm_flush_tlb_entry
EXTRN	?memset@@YAPAXPAXDI@Z:PROC			; memset
EXTRN	?pmm_alloc_block@@YAPAXXZ:PROC			; pmm_alloc_block
EXTRN	?pmm_free_block@@YAXPAX@Z:PROC			; pmm_free_block
_BSS	SEGMENT
__vmm_cur_dir DD 01H DUP (?)
_BSS	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
_addr$ = 8						; size = 4
?vmm_flush_tlb_entry@@YAXI@Z PROC			; vmm_flush_tlb_entry

; 34   : 	_asm{
; 35   : 		cli 

	cli

; 36   : 		invlpg addr 

	invlpg	DWORD PTR _addr$[esp-4]

; 37   : 		sti

	sti

; 38   : 	}
; 39   : }

	ret	0
?vmm_flush_tlb_entry@@YAXI@Z ENDP			; vmm_flush_tlb_entry
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pd_switch@@YA_NPAUpdir@@@Z
_TEXT	SEGMENT
_dir$ = 8						; size = 4
_pd$ = 8						; size = 4
?vmm_pd_switch@@YA_NPAUpdir@@@Z PROC			; vmm_pd_switch, COMDAT

; 25   : 	if (!pd)

	mov	eax, DWORD PTR _pd$[esp-4]
	test	eax, eax
	jne	SHORT $LN1@vmm_pd_swi

; 26   : 		return false;

	xor	al, al

; 31   : }

	ret	0
$LN1@vmm_pd_swi:

; 27   : 
; 28   : 	_vmm_cur_dir = pd;

	mov	DWORD PTR __vmm_cur_dir, eax

; 29   : 	vmm_load_pdbr((pdir*)&_vmm_cur_dir->entry);

	mov	DWORD PTR _dir$[esp-4], eax
	mov	eax, DWORD PTR _dir$[esp-4]
	mov	cr3, eax

; 30   : 	return true;

	mov	al, 1

; 31   : }

	ret	0
?vmm_pd_switch@@YA_NPAUpdir@@@Z ENDP			; vmm_pd_switch
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
_b$ = 8							; size = 1
?vmm_paging_enable@@YAX_N@Z PROC			; vmm_paging_enable

; 120  : void vmm_paging_enable(bool b){

	push	ebp
	mov	ebp, esp

; 121  : 	_asm {
; 122  : 		mov eax, cr0

	mov	eax, cr0

; 123  : 		cmp byte ptr[b],1

	cmp	BYTE PTR _b$[ebp], 1

; 124  : 		jnz fal

	jne	SHORT $fal$4

; 125  : 		or eax, 0x80000000; Bit 31 (PG) : Enables Memory Paging.

	or	eax, -2147483648			; 80000000H

; 126  : 		jmp set

	jmp	SHORT $set$5
$fal$4:

; 127  : 	fal:
; 128  : 		and eax, 0x7FFFFFFF; clear Bit 31 (PG) : Enables Memory Paging.

	and	eax, 2147483647				; 7fffffffH
$set$5:

; 129  : 	set:
; 130  : 		mov cr0, eax

	mov	cr0, eax

; 131  : 	}
; 132  : }

	pop	ebp
	ret	0
?vmm_paging_enable@@YAX_N@Z ENDP			; vmm_paging_enable
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pt_entry_is_writable@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?vmm_pt_entry_is_writable@@YA_NI@Z PROC			; vmm_pt_entry_is_writable, COMDAT

; 159  : 	return e & VMM_PT_ENTRY_WRITABLE;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 1
	and	al, 1

; 160  : }

	ret	0
?vmm_pt_entry_is_writable@@YA_NI@Z ENDP			; vmm_pt_entry_is_writable
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pt_entry_is_present@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?vmm_pt_entry_is_present@@YA_NI@Z PROC			; vmm_pt_entry_is_present, COMDAT

; 155  : 	return e & VMM_PT_ENTRY_PRESENT;

	mov	eax, DWORD PTR _e$[esp-4]
	and	eax, 1

; 156  : }

	ret	0
?vmm_pt_entry_is_present@@YA_NI@Z ENDP			; vmm_pt_entry_is_present
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pt_entry_set_frame@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_addr$ = 12						; size = 4
?vmm_pt_entry_set_frame@@YAXPAII@Z PROC			; vmm_pt_entry_set_frame, COMDAT

; 151  : 	*e = (*e & ~VMM_PT_ENTRY_FRAME) | addr;

	mov	ecx, DWORD PTR _e$[esp-4]
	mov	eax, DWORD PTR [ecx]
	and	eax, -2147479553			; 80000fffH
	or	eax, DWORD PTR _addr$[esp-4]
	mov	DWORD PTR [ecx], eax

; 152  : }

	ret	0
?vmm_pt_entry_set_frame@@YAXPAII@Z ENDP			; vmm_pt_entry_set_frame
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pt_entry_del_attrib@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attrib$ = 12						; size = 4
?vmm_pt_entry_del_attrib@@YAXPAII@Z PROC		; vmm_pt_entry_del_attrib, COMDAT

; 147  : 	*e &= ~attrib;

	mov	eax, DWORD PTR _e$[esp-4]
	mov	ecx, DWORD PTR _attrib$[esp-4]
	not	ecx
	and	DWORD PTR [eax], ecx

; 148  : }

	ret	0
?vmm_pt_entry_del_attrib@@YAXPAII@Z ENDP		; vmm_pt_entry_del_attrib
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pt_entry_add_attrib@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attrib$ = 12						; size = 4
?vmm_pt_entry_add_attrib@@YAXPAII@Z PROC		; vmm_pt_entry_add_attrib, COMDAT

; 143  : 	*e |= attrib;

	mov	ecx, DWORD PTR _e$[esp-4]
	mov	eax, DWORD PTR _attrib$[esp-4]
	or	DWORD PTR [ecx], eax

; 144  : }

	ret	0
?vmm_pt_entry_add_attrib@@YAXPAII@Z ENDP		; vmm_pt_entry_add_attrib
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pd_entry_is_4mb@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?vmm_pd_entry_is_4mb@@YA_NI@Z PROC			; vmm_pd_entry_is_4mb, COMDAT

; 187  : 	return e & VMM_PD_ENTRY_4MB;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 7
	and	al, 1

; 188  : }

	ret	0
?vmm_pd_entry_is_4mb@@YA_NI@Z ENDP			; vmm_pd_entry_is_4mb
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pd_entry_is_user@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?vmm_pd_entry_is_user@@YA_NI@Z PROC			; vmm_pd_entry_is_user, COMDAT

; 183  : 	return e & VMM_PD_ENTRY_USER;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 2
	and	al, 1

; 184  : }

	ret	0
?vmm_pd_entry_is_user@@YA_NI@Z ENDP			; vmm_pd_entry_is_user
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pd_entry_is_present@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?vmm_pd_entry_is_present@@YA_NI@Z PROC			; vmm_pd_entry_is_present, COMDAT

; 175  : 	return e & VMM_PD_ENTRY_PRESENT;

	mov	eax, DWORD PTR _e$[esp-4]
	and	eax, 1

; 176  : }

	ret	0
?vmm_pd_entry_is_present@@YA_NI@Z ENDP			; vmm_pd_entry_is_present
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pd_entry_set_frame@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_addr$ = 12						; size = 4
?vmm_pd_entry_set_frame@@YAXPAII@Z PROC			; vmm_pd_entry_set_frame, COMDAT

; 171  : 	*e = (*e & ~VMM_PD_ENTRY_FRAME) | addr;

	mov	ecx, DWORD PTR _e$[esp-4]
	mov	eax, DWORD PTR [ecx]
	and	eax, -2147479553			; 80000fffH
	or	eax, DWORD PTR _addr$[esp-4]
	mov	DWORD PTR [ecx], eax

; 172  : }

	ret	0
?vmm_pd_entry_set_frame@@YAXPAII@Z ENDP			; vmm_pd_entry_set_frame
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pd_entry_del_attrib@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attrib$ = 12						; size = 4
?vmm_pd_entry_del_attrib@@YAXPAII@Z PROC		; vmm_pd_entry_del_attrib, COMDAT

; 167  : 	*e &= ~attrib;

	mov	eax, DWORD PTR _e$[esp-4]
	mov	ecx, DWORD PTR _attrib$[esp-4]
	not	ecx
	and	DWORD PTR [eax], ecx

; 168  : }

	ret	0
?vmm_pd_entry_del_attrib@@YAXPAII@Z ENDP		; vmm_pd_entry_del_attrib
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
;	COMDAT ?vmm_pd_entry_add_attrib@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attrib$ = 12						; size = 4
?vmm_pd_entry_add_attrib@@YAXPAII@Z PROC		; vmm_pd_entry_add_attrib, COMDAT

; 163  : 	*e |= attrib;

	mov	ecx, DWORD PTR _e$[esp-4]
	mov	eax, DWORD PTR _attrib$[esp-4]
	or	DWORD PTR [ecx], eax

; 164  : }

	ret	0
?vmm_pd_entry_add_attrib@@YAXPAII@Z ENDP		; vmm_pd_entry_add_attrib
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
_dir$ = -8						; size = 4
_b$ = -4						; size = 1
?vmm_initialize@@YAXXZ PROC				; vmm_initialize

; 88   : void vmm_initialize(){

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	push	edi

; 89   : 	ptable * pt_first4mb = (ptable * )pmm_alloc_block();

	call	?pmm_alloc_block@@YAPAXXZ		; pmm_alloc_block
	mov	edi, eax

; 90   : 	if (!pt_first4mb)

	test	edi, edi
	je	$LN17@vmm_initia

; 91   : 		return;
; 92   : 	ptable * pt_1mb_to_3gb = (ptable *)pmm_alloc_block();

	push	ebx
	call	?pmm_alloc_block@@YAPAXXZ		; pmm_alloc_block
	mov	ebx, eax

; 93   : 	if (!pt_1mb_to_3gb)

	test	ebx, ebx
	je	$LN31@vmm_initia

; 94   : 		return;
; 95   : 	/* Map 1st 4Mb (phys) to 1st 4Mb (virt) - identity map */
; 96   : 	for (uint32_t i = 0, frame = 0; i < 1024; i++, frame += 4096)

	push	esi
	xor	esi, esi
	xor	edx, edx
	npad	5
$LL23@vmm_initia:

; 97   : 		pt_first4mb->entry[i] = frame | VMM_PT_ENTRY_PRESENT;

	mov	ecx, esi
	add	esi, 4096				; 00001000H
	or	ecx, 1
	mov	DWORD PTR [edi+edx*4], ecx
	inc	edx
	cmp	edx, 1024				; 00000400H
	jb	SHORT $LL23@vmm_initia

; 98   : 	
; 99   : 	for (uint32_t i = 0, frame = 0x100000; i < 1024; i++, frame += 4096)

	mov	edx, 1048576				; 00100000H
	xor	ecx, ecx
	npad	2
$LL25@vmm_initia:

; 100  : 		pt_1mb_to_3gb->entry[i] = frame | VMM_PT_ENTRY_PRESENT;

	mov	eax, edx
	add	edx, 4096				; 00001000H
	or	eax, 1
	mov	DWORD PTR [ebx+ecx*4], eax
	inc	ecx
	cmp	ecx, 1024				; 00000400H
	jb	SHORT $LL25@vmm_initia

; 101  : 
; 102  : 	/*set Page table to page directory*/
; 103  : 	pdir *dir = (pdir*) pmm_alloc_block();

	call	?pmm_alloc_block@@YAPAXXZ		; pmm_alloc_block
	mov	esi, eax

; 104  : 	if (!dir)

	test	esi, esi
	je	SHORT $LN32@vmm_initia

; 105  : 		return;
; 106  : 
; 107  : 	memset(dir, 0, sizeof(pdir));

	push	4096					; 00001000H
	push	0
	push	esi
	call	?memset@@YAPAXPAXDI@Z			; memset

; 108  : 	dir->entry[0] = (pd_entry)pt_first4mb | VMM_PT_ENTRY_PRESENT | VMM_PT_ENTRY_WRITABLE;

	or	edi, 3

; 109  : 	dir->entry[VMM_GET_PD_ENTRY(0xC0000000)] = (pt_entry)pt_1mb_to_3gb | VMM_PT_ENTRY_PRESENT | VMM_PT_ENTRY_WRITABLE;
; 110  : 
; 111  : 	/*Set Page Directory Base Address*/
; 112  : 	vmm_pd_switch (dir);

	mov	DWORD PTR __vmm_cur_dir, esi
	add	esp, 12					; 0000000cH
	mov	DWORD PTR [esi], edi
	or	ebx, 3
	mov	DWORD PTR _dir$[ebp], esi
	mov	DWORD PTR [esi+3072], ebx
	mov	eax, DWORD PTR _dir$[ebp]
	mov	cr3, eax

; 113  : 
; 114  : 	/* paging Enable */
; 115  : 	vmm_paging_enable(true);

	mov	BYTE PTR _b$[ebp], 1
	mov	eax, cr0
	cmp	BYTE PTR _b$[ebp], 1
	jne	SHORT $fal$34
	or	eax, -2147483648			; 80000000H
	jmp	SHORT $set$35
$fal$34:
	and	eax, 2147483647				; 7fffffffH
$set$35:
	mov	cr0, eax
$LN32@vmm_initia:
	pop	esi
$LN31@vmm_initia:
	pop	ebx
$LN17@vmm_initia:
	pop	edi

; 116  : 
; 117  : }

	mov	esp, ebp
	pop	ebp
	ret	0
?vmm_initialize@@YAXXZ ENDP				; vmm_initialize
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
_phys$ = 8						; size = 4
_virt$ = 12						; size = 4
?vmm_map_page@@YAXPAX0@Z PROC				; vmm_map_page

; 62   : 	pdir *dir = _vmm_cur_dir;
; 63   : 	pd_entry *pde = (pd_entry *)&dir->entry[VMM_GET_PD_ENTRY((pd_entry)virt)];

	mov	eax, DWORD PTR __vmm_cur_dir
	push	ebx
	push	esi
	mov	esi, DWORD PTR _virt$[esp+4]
	mov	ecx, esi
	shr	ecx, 22					; 00000016H

; 64   : 	if (!(*pde&VMM_PT_ENTRY_PRESENT)){

	test	BYTE PTR [eax+ecx*4], 1
	push	edi
	lea	edi, DWORD PTR [eax+ecx*4]
	jne	SHORT $LN9@vmm_map_pa

; 65   : 		//! page table not present, allocate it
; 66   : 		ptable* table = (ptable*)pmm_alloc_block();

	call	?pmm_alloc_block@@YAPAXXZ		; pmm_alloc_block
	mov	ebx, eax

; 67   : 		if (!table)

	test	ebx, ebx
	je	SHORT $LN13@vmm_map_pa

; 68   : 			return;
; 69   : 
; 70   : 		//! clear page table
; 71   : 		memset(table, 0, sizeof(ptable));

	push	4096					; 00001000H
	push	0
	push	ebx
	call	?memset@@YAPAXPAXDI@Z			; memset

; 72   : 
; 73   : 		//! create a new entry
; 74   : 		pd_entry* entry = &dir->entry[VMM_GET_PD_ENTRY((uint32_t)virt)];
; 75   : 
; 76   : 		//! map in the table (Can also just do *entry |= 3) to enable these bits
; 77   : 		vmm_pd_entry_add_attrib(entry, VMM_PT_ENTRY_PRESENT);
; 78   : 		vmm_pd_entry_add_attrib(entry, VMM_PT_ENTRY_WRITABLE);
; 79   : 		vmm_pd_entry_set_frame(entry, (physical_addr)table);

	mov	eax, DWORD PTR [edi]
	add	esp, 12					; 0000000cH
	and	eax, -2147479553			; 80000fffH
	or	eax, ebx
	or	eax, 3
	mov	DWORD PTR [edi], eax
$LN9@vmm_map_pa:

; 80   : 		
; 81   : 	}
; 82   : 	ptable *table = (ptable *)(*pde& ~0xfff);

	mov	eax, DWORD PTR [edi]
	and	eax, -4096				; fffff000H

; 83   : 	pt_entry *page = &table->entry[VMM_GET_PT_ENTRY((pt_entry)virt)];

	shr	esi, 12					; 0000000cH
	and	esi, 1023				; 000003ffH
	lea	ecx, DWORD PTR [eax+esi*4]

; 84   : 	vmm_pt_entry_set_frame(page, (physical_addr)phys);

	mov	eax, DWORD PTR [ecx]
	and	eax, -2147479553			; 80000fffH

; 85   : 	vmm_pt_entry_add_attrib(page, VMM_PT_ENTRY_PRESENT);

	or	eax, DWORD PTR _phys$[esp+8]
	or	eax, 1
	mov	DWORD PTR [ecx], eax
$LN13@vmm_map_pa:

; 86   : }

	pop	edi
	pop	esi
	pop	ebx
	ret	0
?vmm_map_page@@YAXPAX0@Z ENDP				; vmm_map_page
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
_pe$ = 8						; size = 4
?vmm_free_frame@@YA_NPAI@Z PROC				; vmm_free_frame

; 55   : bool vmm_free_frame (pt_entry * pe){

	push	esi

; 56   : 	pmm_free_block(pe); /*Maybe this wrong because we send Address of entry ?*/

	mov	esi, DWORD PTR _pe$[esp]
	push	esi
	call	?pmm_free_block@@YAXPAX@Z		; pmm_free_block

; 57   : 	vmm_pt_entry_del_attrib(pe, VMM_PT_ENTRY_PRESENT);

	and	DWORD PTR [esi], -2			; fffffffeH
	add	esp, 4

; 58   : 	return true;

	mov	al, 1
	pop	esi

; 59   : }

	ret	0
?vmm_free_frame@@YA_NPAI@Z ENDP				; vmm_free_frame
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
_pe$ = 8						; size = 4
?vmm_alloc_frame@@YA_NPAI@Z PROC			; vmm_alloc_frame

; 47   : 	void *p = pmm_alloc_block();

	call	?pmm_alloc_block@@YAPAXXZ		; pmm_alloc_block
	mov	edx, eax

; 48   : 	if (!p)

	test	edx, edx
	jne	SHORT $LN1@vmm_alloc_

; 49   : 		return false;

	xor	al, al

; 53   : }

	ret	0
$LN1@vmm_alloc_:

; 50   : 	vmm_pt_entry_set_frame(pe, (physical_addr)p);

	mov	ecx, DWORD PTR _pe$[esp-4]
	mov	eax, DWORD PTR [ecx]
	and	eax, -2147479553			; 80000fffH

; 51   : 	vmm_pt_entry_add_attrib(pe, VMM_PT_ENTRY_PRESENT);

	or	eax, edx
	or	eax, 1
	mov	DWORD PTR [ecx], eax

; 52   : 	return true;

	mov	al, 1

; 53   : }

	ret	0
?vmm_alloc_frame@@YA_NPAI@Z ENDP			; vmm_alloc_frame
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
?vmm_get_cur_dir@@YAPAUpdir@@XZ PROC			; vmm_get_cur_dir

; 43   : 	return _vmm_cur_dir;

	mov	eax, DWORD PTR __vmm_cur_dir

; 44   : }

	ret	0
?vmm_get_cur_dir@@YAPAUpdir@@XZ ENDP			; vmm_get_cur_dir
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\ali\desktop\mangos\systemcore\syscore\kernel\vmm.cpp
_TEXT	SEGMENT
_dir$ = 8						; size = 4
?vmm_load_pdbr@@YAXPAUpdir@@@Z PROC			; vmm_load_pdbr

; 136  : 	_asm {
; 137  : 		mov eax, dword ptr[dir]

	mov	eax, DWORD PTR _dir$[esp-4]

; 138  : 		mov cr3, eax

	mov	cr3, eax

; 139  : 	}
; 140  : }

	ret	0
?vmm_load_pdbr@@YAXPAUpdir@@@Z ENDP			; vmm_load_pdbr
_TEXT	ENDS
END
